language: node_js
os: linux
dist: xenial

install:
  - npm install
  - npm run build

jobs:
  include:

    - stage: Test
      node_js: 8
      script:
        - npm run cover
    - node_js: 10
      script:
        - npm run cover
    - node_js: 12
      script:
        - npm run cover
    - node_js: lts/*
      script:
        - npm run cover
      # Send coverage data using only a single version of node (else we get duplicate data)
      after_script: cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js
